### ISSUE TITLE
Request : Demo Video

### ISSUE THREAD

**Issue by LiquidViper** [som3canadian/Cloudflare-Redirector#2]
Can you make a demo video for the tool? I have read your document many times, but I still don't understand how to use the tool.

**Comment by som3canadian** [comment]
Hey, thanks for reaching out.

Can you elaborate a little more ?

In general, most of the errors will be about CloudFlare configuration in config.json. Make sure your tunnel is working correctly. Test without redirector(workers) first. If your agent is working with the hostname set in your CF tunnel (screenshot6), it should work with the redirector after. I can add you on discord if you want, will be easier.
